import {
  useCallback,
  useEffect,
  useState,
} from "react";

import type {
  ClusterEvent,
} from "./types/events";

import type {
  NodeInfo,
} from "./types/cluster";

import ClusterView from "./components/ClusterView";
import EventTimeline from "./components/EventTimeline";

import DataOperationsPage from "./pages/DataOperationsPage";

import { getClusterEvents } from "./api/DataApi";

import {
  getClusterStatus,
  removeNode,
  restartNode,
} from "./api/ClusterApi";

function App() {
  const [page, setPage] = useState<
    "cluster" | "data"
  >("cluster");

  const [leaderId, setLeaderId] =
    useState<string | null>(null);

  const [nodes, setNodes] =
    useState<NodeInfo[]>([]);

  const [loading, setLoading] =
    useState(false);

  const [error, setError] =
    useState<string | null>(null);

  const [events, setEvents] =
    useState<ClusterEvent[]>([]);

  /*
   * Refresh cluster state from backend.
   */
  const refreshCluster =
    useCallback(async () => {
      setLoading(true);
      setError(null);

      try {
        const clusterStatus =
          await getClusterStatus();

        setLeaderId(
          clusterStatus.leader_id
        );

        setNodes(
          clusterStatus.nodes
        );
      } catch (error) {
        console.error(
          "Failed to refresh cluster:",
          error
        );

        setError(
          error instanceof Error
            ? error.message
            : "Failed to refresh cluster"
        );
      } finally {
        setLoading(false);
      }
    }, []);


  /* Event handling */
  const handleEvent = useCallback(
    (event: ClusterEvent) => {
      setEvents((previousEvents) => {
        if (previousEvents.some(({ id }) => id === event.id)) {
          return previousEvents;
        }

        return [...previousEvents, event];
      });
    },
    []
  );    

  /*
   * Remove node.
   */
  async function handleRemoveNode(
    nodeId: string
  ) {
    try {
      const previousLeaderId =
        leaderId;

      await removeNode(nodeId);

      const status =
        await getClusterStatus();

      const newLeaderId =
        status.leader_id;

      setNodes(
        status.nodes
      );

      setLeaderId(
        newLeaderId
      );

      setEvents(
        (previousEvents) => {
          const newEvents: ClusterEvent[] = [
            ...previousEvents,

            {
              id: crypto.randomUUID(),
              type: "node_removed",
              nodeId,
              message:
                `Node ${nodeId} was removed from the cluster.`,
              timestamp:
                new Date().toISOString(),
            },
          ];

          if (
            previousLeaderId !== null &&
            previousLeaderId !==
              newLeaderId
          ) {
            newEvents.push({
              id: crypto.randomUUID(),
              type: "leader_elected",
              nodeId:
                newLeaderId ?? "",
              message:
                newLeaderId
                  ? `Leader changed from ${previousLeaderId} to ${newLeaderId}.`
                  : `Leader ${previousLeaderId} was removed. No leader is currently available.`,
              timestamp:
                new Date().toISOString(),
            });
          }

          return newEvents;
        }
      );
    } catch (error) {
      console.error(
        `Failed to remove node ${nodeId}:`,
        error
      );
    }
  }

  /*
   * Restart node.
   */
  async function handleRestartNode(
    nodeId: string
  ) {
    try {
      await restartNode(nodeId);

      setEvents(
        (previousEvents) => [
          ...previousEvents,

          {
            id: crypto.randomUUID(),
            type: "node_restarted",
            nodeId,
            message:
              `Node ${nodeId} was restarted and added back to the cluster.`,
            timestamp:
              new Date().toISOString(),
          },
        ]
      );

      await refreshCluster();
    } catch (error) {
      console.error(
        `Failed to restart node ${nodeId}:`,
        error
      );
    }
  }

  /*
   * Handle a successful data operation.
   *
   * WRITE:
   *   Leader -> write_direct
   *   Followers -> write_replicated
   *
   * READ:
   *   Leader -> read_operation
   */
  function handleDataOperation(
    operation: "read" | "write",
    key: string,
    value: unknown,
    backendEvents?: ClusterEvent[],
  ){
    const timestamp =
      new Date().toISOString();


    /*
    * WRITE
    *
    * Use events generated by backend.
    */
    if (operation === "write") {

      if (backendEvents) {
        console.log(
          "[EVENT] Adding backend events:",
          backendEvents
        );

        setEvents(
          previousEvents => [
            ...previousEvents,
            ...backendEvents.map(event => ({
              ...event,
              id: crypto.randomUUID(),
            })),
          ]
        );
      }

      return;
    }


    /*
    * READ
    */
    if (operation === "read") {

      if (!leaderId) {
        console.warn(
          "Cannot record read event because there is no leader."
        );

        return;
      }


      const readEvent: ClusterEvent = {
        id: crypto.randomUUID(),
        type: "read_operation",
        nodeId: leaderId,
        message:
          `Read "${key}".`,
        timestamp,
        key,
        value,
      };


      console.log(
        "[EVENT] Adding read event:",
        readEvent
      );


      setEvents(
        previousEvents => [
          ...previousEvents,
          readEvent,
        ]
      );
    }
  }

  /*
   * Initial cluster load.
   */
  useEffect(() => {
    refreshCluster();
  }, [refreshCluster]);

  /*
   * A write response contains the leader event immediately. Follower events
   * arrive asynchronously, so collect them from the backend event queue.
   */
  useEffect(() => {
    let cancelled = false;

    const collectEvents = async () => {
      try {
        const backendEvents = await getClusterEvents();

        if (!cancelled) {
          backendEvents.forEach(handleEvent);
        }
      } catch (error) {
        // Event polling should not hide otherwise successful data operations.
        console.error("Failed to retrieve cluster events:", error);
      }
    };

    void collectEvents();
    const intervalId = window.setInterval(() => {
      void collectEvents();
    }, 500);

    return () => {
      cancelled = true;
      window.clearInterval(intervalId);
    };
  }, [handleEvent]);

  return (
    <main>
      <header>
        <h1>
          Single-Leader Replication Cluster
        </h1>

        <nav>
          <button
            onClick={() =>
              setPage("cluster")
            }
            disabled={
              page === "cluster"
            }
          >
            Cluster Overview
          </button>

          <button
            onClick={() =>
              setPage("data")
            }
            disabled={
              page === "data"
            }
          >
            Data Operations
          </button>
        </nav>
      </header>

      {error && (
        <p role="alert">
          Error: {error}
        </p>
      )}

      {page === "cluster" && (
        <>
          <button
            onClick={refreshCluster}
            disabled={loading}
          >
            {loading
              ? "Refreshing..."
              : "Refresh cluster"}
          </button>

          <ClusterView
            leaderId={leaderId}
            nodes={nodes}
            onRemoveNode={
              handleRemoveNode
            }
            onRestartNode={
              handleRestartNode
            }
          />

          <EventTimeline
            events={events}
          />
        </>
      )}

      {page === "data" && (
        <DataOperationsPage
          nodes={nodes}
          leaderId={leaderId}
          events={events}
          onClusterUpdated={refreshCluster}
          onEvent={handleEvent}
          onDataOperation={handleDataOperation}
        />
      )}
    </main>
  );
}

export default App;
